config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  # authenticated :user do
  #   root :to => 'users#show'
  # end
  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
    member do
      get 'update_interests'
    end
  end

  match "/index" => "home#index"
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to image_tag("logo.png", :alt=>"SOCIALIZE",  :width=>"200"), root_path, class: "brand" %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'My account', user_path(id: current_user) %>
    </li>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <li>
    <%= link_to 'Update Interests', update_interests_user_path(id: current_user.id) %>
    </li>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    </li>
  <% else %>
    <li>
    <%= link_to image_tag("button.png"), user_omniauth_authorize_path(:facebook) %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Socialize" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Bootstrap Devise Cancan" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= yield :scripts %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>

          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>